### ISSUE TITLE
Insert component does not work inside slide-over component

### ISSUE THREAD

**Issue by amshehzad** [wire-elements/pro-demo#1]
Hi, I just purchased the livewire pro components and could not find any repo for it so I'm opening the issue here ( sorry about that )
I'm using the insert component and it works great except that it is not working inside slide-over component. 
I tried it in modal component and it works well there but it only not works in slid-over.

Thank you

**Comment by PhiloNL** [comment]
Hi @amshehzad,

Thanks for reaching out and for your support. Drop me an email at support@wire-elements.dev, and I'll invite you to join our Discord server to discuss this further.

Thanks!
