### ISSUE TITLE
HTML stays overflow:hidden after closing a SlideOver

### ISSUE THREAD

**Issue by GuyVervillePerso** [wire-elements/pro-demo#13]
Hi,
I realized that the entire HTML is devoid of scrolling after closing a SlideOver. The local styles should be removed entirely at closing.

![CleanShot 2024-09-09 at 09 56 46@2x](https://github.com/user-attachments/assets/01c1cbce-402c-4351-a19a-74086ab695ef)

I am writing this here because there seems no way to contact you.

**Comment by GuyVervillePerso** [comment]
I realize that I can destroy the "state" in config. Should be more documented, perhaps?

**Comment by PhiloNL** [comment]
@GuyVervillePerso the overflow state should be removed. Do you get any console errors by any chance? This also tend to happen with stray unclosed elements or when loading Alpine multiple times.

**Comment by GuyVervillePerso** [comment]
Hi, thank you for answering. The problem seems to have disappear. I don't know what happened. If this comes back, I will let you know.
