### ISSUE TITLE
Scope does not work in the insert component

### ISSUE THREAD

**Issue by amshehzad** [wire-elements/pro-demo#2]
Hi, I'm trying to use the $scope in the insert component but it does not work. It always passed empty.
I've checked the base search method and find out that it's actually does not have the scope parameter.

**Comment by PhiloNL** [comment]
Sorry for not replying earlier, I don't monitor this repository. You can reach out to [support@wire-elements.dev](mailto:support@wire-elements.dev) if this still is an issue.
