### ISSUE TITLE
Livewire v3 Support Request

### ISSUE THREAD

**Issue by Verstand** [wire-elements/pro-demo#4]
Hello!

I am reaching out to inquire about the possibility of adding support for Livewire v3 to the package. I'm excited about the new features and improvements in Livewire v3 and would love to see them integrated with your package.

As a user of your package, I find it highly beneficial, and having it compatible with the latest version of Livewire would greatly enhance its functionality. I understand that updating a package may require time and effort, but I believe that the advantages it brings will be well worth it.

Could you kindly let me know if there are plans to provide support for Livewire v3? If so, I would like to know the estimated timeframe for the update. Your response will help me make informed decisions regarding my project's development.

Thank you for your attention to this matter. Your efforts are highly appreciated, and I look forward to hearing from you soon.

**Comment by PhiloNL** [comment]
Yes! Read more here https://github.com/wire-elements/modal/discussions/329
