### ISSUE TITLE
Emitting Event Changes in Livewire V3

### ISSUE THREAD

**Issue by Fludem** [wire-elements/pro-demo#6]
Hey,

As emitting events has changed to dispatch() now in Livewire v3 and the syntax compared to emit() is different it can make the documentation confusing as it references methods only usable in Livewire V3.

Might be worth mentioning this in the documentation

**Comment by PhiloNL** [comment]
Sorry, I don't monitor this repo but thanks for mentioning. The old docs are available here: https://v3.wire-elements.dev/docs/getting-started/installation#start
