### ISSUE TITLE
Converted (upgraded) From Modal to Modal-Pro now receiving Alpine Errors

### ISSUE THREAD

**Issue by soccerjf** [wire-elements/pro-demo#7]
Not sure if I've missed a step in converting over (or if this is the right repository to use) but I'm now getting a number of Alpine errors, summarized below but I suspect they're all related to a missed step.
These errors all begins with: Alpine Expression Error: Illegal invocation
Expression: "open" div.wep-modal
Expression: "open" div.wep-modal-backdrop

WepOverlayComponent is not definedExpression: "WepOverlayComponent({ type: 'modal', animationOverlapDuration: 350 })"

Thxs in advance for your help.

**Comment by EriksonEnterprises** [comment]
I'm getting the same - did you ever figure it out? Feeling like I got ripped off now :/

**Comment by PhiloNL** [comment]
Sorry for not replying earlier, I don't monitor this repository. You can reach out to support@wire-elements.dev to report any issues. As for the error, you might have missed a step when converting / setting up Wire Elements Pro. Also make sure you are not loading Alpine twice. 

If the issue still persist, the best way to solve it is to fork this pro-demo repository and replicate the problem you are experiencing and send this to me so I can investigate.
