### ISSUE TITLE
Laravel 11 Support missing

### ISSUE THREAD

**Issue by eddierusinskas** [wire-elements/pro-demo#9]
Please allow Laravel 11 support within `composer.json` of `wire-elements/pro` package

**Current**

```json
"require": {
      "php": "^8.1",
      "livewire/livewire": "^3.0",
      "spatie/laravel-package-tools": "^1.9.2",
      "illuminate/contracts": "^8.0|^9.0|^10.0"
  }
```

**Laravel 11**

```json
"require": {
      "php": "^8.1",
      "livewire/livewire": "^3.0",
      "spatie/laravel-package-tools": "^1.9.2",
      "illuminate/contracts": "^8.0|^9.0|^10.0|^11.0"
  }
```

Thank you!

**Comment by PhiloNL** [comment]
Hi @eddierusinskas,

Laravel 11 support has been added a month ago:
https://changelog.anystack.sh/wire-elements-pro 

Could it be the case that your license is expired? In that case, you are locked to the latest version that was available on the day your license expired.

**Comment by eddierusinskas** [comment]
Hi @PhiloNL 
I will have a look, it might be that, thank you so much for you reply!
